networks: 
  internal:
    internal: true 

    
services:
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    networks: [internal]
    restart: unless-stopped
    environment:
      DOMAIN: ${VAULTWARDEN_DOMAIN}
    volumes:
      - ./vw-data/:/data/

  caddy:
    image: caddy:2-alpine
    container_name: caddy
    restart: unless-stopped
    ports:
      - ${CADDY_PORT}
    networks: [internal]
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - vaultwarden

volumes:
  caddy_data:
  caddy_config: